## Country name / ISO code → flag emoji (regional-indicator pairs).
class_name CountryFlags
extends RefCounted

const _BY_CODE := {
	"FR": "🇫🇷",
	"BE": "🇧🇪",
	"CH": "🇨🇭",
	"CA": "🇨🇦",
	"US": "🇺🇸",
	"GB": "🇬🇧",
	"UK": "🇬🇧",
	"DE": "🇩🇪",
	"ES": "🇪🇸",
	"IT": "🇮🇹",
	"PT": "🇵🇹",
	"NL": "🇳🇱",
	"LU": "🇱🇺",
	"MC": "🇲🇨",
	"MA": "🇲🇦",
	"DZ": "🇩🇿",
	"TN": "🇹🇳",
	"SN": "🇸🇳",
	"CI": "🇨🇮",
	"BR": "🇧🇷",
	"MX": "🇲🇽",
	"AR": "🇦🇷",
	"JP": "🇯🇵",
	"KR": "🇰🇷",
	"CN": "🇨🇳",
	"IN": "🇮🇳",
	"AU": "🇦🇺",
	"NZ": "🇳🇿",
	"IE": "🇮🇪",
	"PL": "🇵🇱",
	"RO": "🇷🇴",
	"SE": "🇸🇪",
	"NO": "🇳🇴",
	"DK": "🇩🇰",
	"FI": "🇫🇮",
	"GR": "🇬🇷",
	"TR": "🇹🇷",
	"RU": "🇷🇺",
	"UA": "🇺🇦",
	"EG": "🇪🇬",
	"ZA": "🇿🇦",
}

const _BY_NAME := {
	"france": "FR",
	"belgium": "BE",
	"belgique": "BE",
	"switzerland": "CH",
	"suisse": "CH",
	"canada": "CA",
	"united states": "US",
	"usa": "US",
	"états-unis": "US",
	"etats-unis": "US",
	"united kingdom": "GB",
	"uk": "GB",
	"royaume-uni": "GB",
	"germany": "DE",
	"allemagne": "DE",
	"spain": "ES",
	"espagne": "ES",
	"italy": "IT",
	"italie": "IT",
	"portugal": "PT",
	"netherlands": "NL",
	"pays-bas": "NL",
	"luxembourg": "LU",
	"monaco": "MC",
	"morocco": "MA",
	"maroc": "MA",
	"algeria": "DZ",
	"algérie": "DZ",
	"algerie": "DZ",
	"tunisia": "TN",
	"tunisie": "TN",
	"senegal": "SN",
	"sénégal": "SN",
	"ivory coast": "CI",
	"côte d'ivoire": "CI",
	"cote d'ivoire": "CI",
	"brazil": "BR",
	"brésil": "BR",
	"bresil": "BR",
	"mexico": "MX",
	"mexique": "MX",
	"argentina": "AR",
	"argentine": "AR",
	"japan": "JP",
	"japon": "JP",
	"south korea": "KR",
	"corée du sud": "KR",
	"china": "CN",
	"chine": "CN",
	"india": "IN",
	"inde": "IN",
	"australia": "AU",
	"australie": "AU",
	"new zealand": "NZ",
	"nouvelle-zélande": "NZ",
	"ireland": "IE",
	"irlande": "IE",
	"poland": "PL",
	"pologne": "PL",
	"romania": "RO",
	"roumanie": "RO",
	"sweden": "SE",
	"suède": "SE",
	"norway": "NO",
	"norvège": "NO",
	"denmark": "DK",
	"danemark": "DK",
	"finland": "FI",
	"finlande": "FI",
	"greece": "GR",
	"grèce": "GR",
	"turkey": "TR",
	"turquie": "TR",
	"russia": "RU",
	"russie": "RU",
	"ukraine": "UA",
	"egypt": "EG",
	"égypte": "EG",
	"south africa": "ZA",
	"afrique du sud": "ZA",
}


static func emoji_for(country: String) -> String:
	var raw := country.strip_edges()
	if raw.is_empty():
		return "🏳️"
	var upper := raw.to_upper()
	if _BY_CODE.has(upper):
		return str(_BY_CODE[upper])
	var key := raw.to_lower()
	if _BY_NAME.has(key):
		var code: String = str(_BY_NAME[key])
		return str(_BY_CODE.get(code, "🏳️"))
	return "🏳️"


static func label(country: String) -> String:
	return "%s  %s" % [emoji_for(country), country.strip_edges()]
